const hotels = [
    {
      id: 1,
      title: 'Cozy Cottage',
      address: '123 Garden Lane',
      description: 'A small, cozy cottage with a beautiful garden view.',
      checkIn: '14:00',
      checkOut: '11:00',
      maxGuests: 4,
      price: 150,
      perks: ['garden', 'wifi', 'parking'],
      addedPhotos: [
        'https://example.com/photos/cottage1.jpg',
        'https://example.com/photos/cottage2.jpg',
      ],
      rooms: [
        {
          id: 1,
          title: 'Garden View Room',
          description: 'A room with a view of the garden.',
          bedCount: 1,
          guestCount: 2,
          roomPrice: 75,
          bathroomCount: 1,
          freeWifi: true,
          airCondition: false,
          roomService: false,
          balcony: true,
          soundProof: false,
          kingBed: 1,
          queenBed: 0,
          forestView: true,
          cityView: false,
          oceanView: false,
          breakfastPrice: 10,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
        {
          id: 2,
          title: 'Family Suite',
          description: 'A spacious suite suitable for families.',
          bedCount: 2,
          guestCount: 4,
          roomPrice: 120,
          bathroomCount: 2,
          freeWifi: true,
          airCondition: true,
          roomService: true,
          balcony: true,
          soundProof: true,
          kingBed: 1,
          queenBed: 1,
          forestView: true,
          cityView: false,
          oceanView: false,
          breakfastPrice: 15,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
      ],
    },
    {
      id: 2,
      title: 'Mountain Retreat',
      address: '456 Hilltop Road',
      description: 'A serene retreat nestled in the mountains.',
      checkIn: '15:00',
      checkOut: '12:00',
      maxGuests: 6,
      price: 250,
      perks: ['mountain view', 'free breakfast', 'spa'],
      addedPhotos: [
        'https://example.com/photos/mountain1.jpg',
        'https://example.com/photos/mountain2.jpg',
      ],
      rooms: [
        {
          id: 3,
          title: 'Mountain View Room',
          description: 'A room with stunning mountain views.',
          bedCount: 1,
          guestCount: 2,
          roomPrice: 100,
          bathroomCount: 1,
          freeWifi: true,
          airCondition: true,
          roomService: true,
          balcony: true,
          soundProof: false,
          kingBed: 1,
          queenBed: 0,
          forestView: false,
          cityView: false,
          oceanView: false,
          breakfastPrice: 12,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
        {
          id: 4,
          title: 'Suite with Balcony',
          description: 'A luxurious suite with a private balcony.',
          bedCount: 2,
          guestCount: 4,
          roomPrice: 180,
          bathroomCount: 2,
          freeWifi: true,
          airCondition: true,
          roomService: true,
          balcony: true,
          soundProof: true,
          kingBed: 1,
          queenBed: 1,
          forestView: true,
          cityView: true,
          oceanView: false,
          breakfastPrice: 20,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
      ],
    },
    {
      id: 3,
      title: 'City Hotel',
      address: '789 Downtown Ave',
      description: 'Modern hotel in the heart of the city.',
      checkIn: '13:00',
      checkOut: '11:00',
      maxGuests: 8,
      price: 300,
      perks: ['city view', 'gym', 'pool', 'restaurant'],
      addedPhotos: [
        'https://example.com/photos/city1.jpg',
        'https://example.com/photos/city2.jpg',
      ],
      rooms: [
        {
          id: 5,
          title: 'Executive Room',
          description: 'Ideal for business travelers.',
          bedCount: 1,
          guestCount: 2,
          roomPrice: 150,
          bathroomCount: 1,
          freeWifi: true,
          airCondition: true,
          roomService: true,
          balcony: false,
          soundProof: true,
          kingBed: 1,
          queenBed: 0,
          forestView: false,
          cityView: true,
          oceanView: false,
          breakfastPrice: 18,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
        {
          id: 6,
          title: 'Penthouse Suite',
          description: 'A luxurious penthouse with panoramic views.',
          bedCount: 2,
          guestCount: 4,
          roomPrice: 400,
          bathroomCount: 3,
          freeWifi: true,
          airCondition: true,
          roomService: true,
          balcony: true,
          soundProof: true,
          kingBed: 1,
          queenBed: 1,
          forestView: false,
          cityView: true,
          oceanView: true,
          breakfastPrice: 30,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
      ],
    },
    {
      id: 4,
      title: 'Seaside Inn',
      address: '321 Ocean Blvd',
      description: 'A charming inn by the sea.',
      checkIn: '16:00',
      checkOut: '11:00',
      maxGuests: 5,
      price: 180,
      perks: ['ocean view', 'free parking', 'pet-friendly'],
      addedPhotos: [
        'https://example.com/photos/seaside1.jpg',
        'https://example.com/photos/seaside2.jpg',
      ],
      rooms: [
        {
          id: 7,
          title: 'Oceanfront Room',
          description: 'A room with an ocean view and balcony.',
          bedCount: 1,
          guestCount: 2,
          roomPrice: 130,
          bathroomCount: 1,
          freeWifi: true,
          airCondition: true,
          roomService: false,
          balcony: true,
          soundProof: false,
          kingBed: 1,
          queenBed: 0,
          forestView: false,
          cityView: false,
          oceanView: true,
          breakfastPrice: 12,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
      ],
    },
    {
      id: 5,
      title: 'Forest Lodge',
      address: '654 Forest Dr',
      description: 'An eco-friendly lodge surrounded by forest.',
      checkIn: '14:00',
      checkOut: '11:00',
      maxGuests: 3,
      price: 120,
      perks: ['forest view', 'free parking', 'hiking trails'],
      addedPhotos: [
        'https://example.com/photos/forest1.jpg',
        'https://example.com/photos/forest2.jpg',
      ],
      rooms: [
        {
          id: 8,
          title: 'Forest Cabin',
          description: 'A private cabin with forest views.',
          bedCount: 1,
          guestCount: 2,
          roomPrice: 90,
          bathroomCount: 1,
          freeWifi: false,
          airCondition: false,
          roomService: false,
          balcony: false,
          soundProof: false,
          kingBed: 1,
          queenBed: 0,
          forestView: true,
          cityView: false,
          oceanView: false,
          breakfastPrice: 8,
          reservations: [
            { userId: 'user1', startDate: '2024-10-15', endDate: '2024-10-17' },
            { userId: 'user2', startDate: '2024-11-01', endDate: '2024-11-05' },
          ],
        
        },
      ],
    },
  ];
