import DashboardWrapper from "@/components/Dashboard/dashboardWrapper"

import '../../app/globals.css'
import ThemeProvider from "@/context/ThemeProvider"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
        <DashboardWrapper>
        {children}
        </DashboardWrapper>

        </ThemeProvider>

        
        </body>
    </html>
  )
}
